- OWNERS
- README.md
A first draft / version of an "OpenShift Console Plugin for Tekton CD / OpenShift Pipelines" README.
Kept the helm section untouched to update it together with the helm chart.
Added @saumeya to the reviewer list.
> ODC-7411: Update README: Remove/rewrote templates related content in favor of pipeline-console-plugin content

- integration-tests/cypress.config.js
- integration-tests/tests/example.cy.ts
- package.json
Created one minimal cypress test (based on https://github.com/openshift/console-plugin-template/blob/main/integration-tests/tests/example-page.cy.ts), otherwise `yarn test-cypress-headless` fails with:
```
yarn run v1.22.19
$ cd integration-tests && node --max-old-space-size=4096 ../node_modules/.bin/cypress run --env openshift=true --browser ${BRIDGE_E2E_BROWSER_NAME:=chrome}
Can't run because no spec files were found.
We searched for specs matching this glob pattern:
> /home/christoph/git/openshift-pipelines/console-plugin/integration-tests/tests/**/*.cy.{js,jsx,ts,tsx}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
> ODC-7412: Fix e2e failues by having at least one working cypress test example

- src/components/pipelines-metrics/PipelinesAverageDuration.tsx
- src/components/pipelines-overview/PipelineRunsDurationCard.scss
- src/components/pipelines-overview/PipelineRunsDurationCard.tsx
- src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
- src/components/pipelines-overview/PipelineRunsStatusCard.tsx
- src/components/pipelines-overview/PipelineRunsTotalCard.scss
- src/components/pipelines-overview/PipelineRunsTotalCard.tsx
Story: https://issues.redhat.com/browse/ODC-7455
Descriptions: 
1. Aligned the numbers to the right in the Duration and Total runs card
2. Charts axis styles (font and color) should be the same for all charts
3. increase the Chart bar width
> ODC-7455: consmetic changes in Charts and number cards

- src/components/pipelines-overview/PipelineRunsTotalCard.tsx
- src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
- src/components/pipelines-overview/utils.ts
This ignores change to the filter ignores PipelineRuns that are started individually.
Solves also a bug that the PipelineRun name was used as Pipeline name in the Pipeline list page. But the click on the Pipeline shows 404.
**Demo PipelineRun:**
```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
generateName: independent-pipeline-
spec:
params:
- name: NAME
value: world
pipelineSpec:
tasks:
- name: echo-hello
taskSpec:
metadata: {}
spec: null
steps:
- computeResources: {}
image: ubuntu
name: echo
script: |
#!/usr/bin/env bash
echo "Hello"
- name: echo-name
runAfter:
- echo-hello
taskSpec:
metadata: {}
spec: null
steps:
- computeResources: {}
image: ubuntu
name: echo
script: |
#!/usr/bin/env bash
echo "$(params.NAME)"
- name: echo-bye
taskSpec:
metadata: {}
spec: null
steps:
- …
```
> ODC-7462: Hide standalone PipelineRuns by req. spec.pipelineRef.name for Pipeline PLRs

- src/components/pipelines-overview/dateTime.ts
Description:
If it is 1st PLR for pipeline and repository, last run time will be shown as '-'. From API last run time is passed as completed timestamp, so show '-' till it gets completed
> fix: For 1st plr show - for last runtime until it is completed

- scripts/install-operator-results-api.sh
This PR adds a scripts for installing the operator and results on the cluster, the user can specify the version of the operator like so :- 
./install-operator-results-api.sh 1.13.1
https://issues.redhat.com/browse/ODC-7417
> ODC-7417: Add scripts for Development setup

- src/components/pipelines-metrics/PipelinesMetricsPage.tsx
- src/components/pipelines-overview/PipelinesOverviewPage.tsx
- src/components/pipelines-overview/RefreshIntervalDropdown.tsx
- src/components/pipelines-overview/SearchInput.tsx
- src/components/pipelines-overview/__tests__/PipelinesOverview.spec.tsx
- src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
- src/components/pipelines-overview/utils.ts
Added support for url params for filters mentioned in the [story](https://issues.redhat.com/browse/ODC-7468) i.e.
- added URL params on Time Range selection
- added URL params on Refresh interval selection
- added URL params on searching the Pipeline/Repository in the list
- added URL params on Per Pipeline/Per Repository selection 
- updated the filters based on params present in the URL.
WIP PR
Todo:
- add URL params on Filter by status in the list
- check issue with loading interval & range with search & pageFlag
> ODC-7468: Add URL params for all filters available on the Pipeline Overview page

- src/components/hooks/flagHookProvider.ts
Fix: [OCPBUGS-28721](https://issues.redhat.com/browse/OCPBUGS-28721)
Descriptions: Metrics tab on the Pipeline details page is not present if the Dynamic plugin is enabled but TektonResult CR is not present on the cluster. So, enable the `FLAG_HIDE_STATIC_PIPELINE_PLUGIN_PIPELINE_DETAIL_METRICS_TAB` flag only if TektonResults CR is present on the cluster.
> OCPBUGS-28721: Enable metrics tab flag if TektonResults CR is present

- src/components/pipelines-metrics/PipelinesAverageDuration.tsx
- src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
- src/components/pipelines-overview/PipelineRunsStatusCard.tsx
Fix logic for week group_by. The group_by API returns the Monday date of the week, which is also the value for the x-axis. Hence no need to add additional logic for checking if the date falls withing the week.
> ODC-7470: fix logic for quarterly week grouping

- .github/workflows/publish_container_image.yaml
Fixes the following issue by syncing the docker login and buildx GH action versions,
```
docker/setup-buildx-action@v1 is not allowed to be used in openshift-pipelines/console-plugin. Actions in this workflow must be: within a repository owned by openshift-pipelines, created by GitHub, or matching the following: docker/login-action@*.
```
> SRVKP-4088: sync docker login and buildx gh action

- .github/workflows/publish_container_image.yaml
- Dockerfile
- Dockerfile.without_builder
- scripts/build_container.sh
* performing `yarn install` on multiarch with `docker buildx` takes a lot of time (approx `2h30m`)
to avoid this, `yarn install` and `yarn build` should be executed outside of docker (on a host platform)
and only copy the `dist` to different platform/architecture runtime containers
**WARNING:** with this approach, if we use platform native package may lead to a malfunction
however in this project, the code will be executed on a browser and assuming there is no platform specific implementations, hence assuming no impact on this approach
* and builds the container image for `release-v*` branches
> SRVKP-4088: [main] tune multiarch container image build time

- console-extensions.json
- package.json
- src/components/hooks/useActiveNamespace.ts
- src/components/pipelines-metrics/PipelinesMetricsPage.tsx
- src/components/pipelines-overview/PipelinesOverviewPage.tsx
- src/components/pipelines-overview/__tests__/PipelinesOverview.spec.tsx
- src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx
- src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesRow.tsx
- src/components/pipelines-overview/utils.ts
- src/components/utils/tekton-results.ts
- src/types/index.ts
- src/types/openshift.ts
- yarn.lock
Fix: [OCPBUGS-28978](https://issues.redhat.com/browse/OCPBUGS-28978)
Descriptions: Remove 'react-router-dom-v5-compat' package and use of useActiveNamespace from the sdk and downgrade the `@openshift-console/dynamic-plugin-sdk` and `@openshift-console/dynamic-plugin-sdk-webpack` to support OCP 4.12 and 4.13. 
as per https://github.com/openshift/console/tree/master/frontend/packages/console-dynamic-plugin-sdk#openshift-console-versions-vs-sdk-versions
> OCPBUGS-28978: Remove 'react-router-dom-v5-compat' package and use of useActiveNamespace from the sdk

- .github/workflows/publish_container_image.yaml
- Dockerfile
- Dockerfile.without_builder
- scripts/build_container.sh
* sync github actions and docker changes with `main` branch
> SRVKP-4116: [v1.14.0] sync github actions and docker changes with main branch

- src/components/pipelines-tasks/tasks-details-pages/TaskRunDetailsPage.tsx
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-31745
**Analysis / Root cause**: 
Status was not added for TaskRun details page heading
Added the status value in heading
**Screen shots / Gifs for design review**: 
---Before--
--After--
**Unit test coverage report**: 
NA
**Test setup:**
1. Create a TaskRun and go to details page
**Browser conformance**:
> OCPBUGS-31745: TaskRun status is not displayed near the name

- src/components/pipelines-list/PipelinesList.tsx
**Issue:**
https://issues.redhat.com/browse/OCPBUGS-33333
----Before----
----After----
**Steps to reproduce:**
1. Install Pipelines operator
2. Install tekton results
3. Create some Pipeline and PipelineRuns
4. Delete PipelineRun and see Pipeline list page, Task Status and Last Run Status is '-'
> [console-plugin] OCPBUGS-33333: In PipelineList page PipelineRuns not fetched from tekton results

- src/components/details-page/DetailsPage.scss
- src/components/details-page/DetailsPage.tsx
> OCPBUGS-33344: Fix details page Actions in dark mode

- console-extensions.json
Issue: The Pipelines nav option is present without the Pipelines operator installed.
> OCPBUGS-33390: Add checks for OPENSHIFT_PIPELINE flag on Pipelines nav

- locales/en/plugin__pipelines-console-plugin.json
- src/components/list-pages/default-resources.tsx
- src/components/pipelines-tasks/TaskRunsList.tsx
> OCPBUGS-35948: Corrected typo Namespace in list page

- src/components/pipelines-metrics/PipelinesAverageDuration.tsx
**Issue:**
https://issues.redhat.com/browse/SRVKP-5836
In Metrics tab of Pipelines/Repository details page, the y-axis of average duration chat is fixed to max of 5 minutes. In this PR, based on the max y axis value, y-axis is set.
> SRVKP-5836: In metrics overview page of tekton results, Average duration chart y-axis is always set to 5m

- src/components/pipelineRuns-details/RepositoryLinkList.tsx
- src/components/pipelineRuns-list/PipelineRunsRow.tsx
- src/components/pipelineRuns-list/usePipelineRunsColumns.ts
- src/components/repositories-list/RepositoriesRow.tsx
- src/components/utils/repository-utils.tsx
- src/consts.ts
- src/test-data/pipeline-data.ts
Fixes: https://issues.redhat.com/browse/SRVKP-5880
Descriptions:
The labels added by PAC have been deprecated and added to PLR annotations. So, use annotations to get the value in the repository list page, repository PLRs list page, and on the PLR details page.
Test steps:
Check Repository list page
PipelineRuns list page for repository
PipelineRun details page
Repository details page
> SRVKP-5880: Switch to use annotations as labels from PipelineRuns created through Pipelines as Code is deprecated

- src/components/pipelineRuns-details/RepositoryLinkList.tsx
- src/components/pipelineRuns-list/PipelineRunsRow.tsx
- src/components/pipelineRuns-list/usePipelineRunsColumns.ts
- src/components/repositories-list/RepositoriesRow.tsx
- src/components/utils/repository-utils.tsx
- src/consts.ts
manual cherry-pick of https://github.com/openshift-pipelines/console-plugin/pull/131
> [release-v1.15.x] SRVKP-5880: Switch to use annotations as labels from PipelineRuns created through Pipelines as Code is deprecated

- src/components/modals/LoadingModal.tsx
- src/components/modals/modal.tsx
**Issue:**
https://issues.redhat.com/browse/SRVKP-5936
**Analysis / Root cause**: 
onClose function was not submitted to Modal component.
Added onClose function to Modal component. 
**Screen shots / Gifs for design review**: 
----BEFORE---
https://github.com/user-attachments/assets/211ff1b6-d73a-47b9-b649-f5b9beb19e26
---AFTER---
https://github.com/user-attachments/assets/401d9b34-3637-4b7e-864b-1308dd1074b2
**Unit test coverage report**: 
NA
**Test setup:**
1. Install Pipelines operator and enable dynamic plugin
2. Create a pipeline and click on start in kebab menu
3. Click on X button to close the start pipeline modal
**Browser conformance**:
> SRVKP-5936: Close modal button is not working in dynamic plugin list pages

- __mocks__/serverFlags.js
- integration-tests/cypress/features/pipelines/pipelines-runs.feature
- integration-tests/cypress/support/page-objects/pipelines-po.ts
- integration-tests/cypress/support/pages/app.ts
- integration-tests/cypress/support/pages/functions/common.ts
- integration-tests/cypress/support/pages/functions/installOperatorOnCluster.ts
- integration-tests/cypress/support/pages/git-page.ts
- integration-tests/cypress/support/pages/pipelines/pipelineRun-details-page.ts
- integration-tests/cypress/support/pages/pipelines/pipelines-page.ts
- integration-tests/cypress/support/pages/topology-page.ts
- integration-tests/cypress/support/step-definitions/common/pipelines.ts
- integration-tests/cypress/support/step-definitions/pipelines/create-from-add-options.ts
- integration-tests/cypress/support/step-definitions/pipelines/pipelines-runs.ts
- yarn.lock
Story:[ODC-7601](https://issues.redhat.com/browse/ODC-7601)
Description:
Adding e2e test for the new timeout option
Command to execute:
export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.13-042801.devcluster.openshift.com/
export BRIDGE_KUBEADMIN_PASSWORD
export BRIDGE_BASE_ADDRESS
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
oc apply -f ./tests/utils/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./tests/utils/patch-htpasswd.yaml)" --type=merge
./test-prow-e2e.sh -h false
Run pipelines-runs.feature
Check for second test case
Browser:
Chrome 125
Screenshot:
> ODC-7601: Add e2e test for the new timeout option

- console-extensions.json
- src/components/pipelineRuns-details/LogURLRedirect.tsx
- src/components/pipelineRuns-details/index.ts
Descriptions: Logs URL has been changed after the react-router package upgrade because of this change log URL provided by PAC is broken now. This change redirects the old PLR logs URL to a new one.
> SRVKP-6101: Redirects to new PipelineRun logs URL from old PipelineRun logs URL

- .github/workflows/publish_container_image.yaml
- Dockerfile
- Dockerfile.without_builder
* bumps node version to `1.18` on GitHub actions
* bumps cache module version in GitHub actions
* bumps ngnix image to supported version
> SRVKP-6232: [main] bump node version and nginx image

- src/components/hooks/useTektonResult.ts
- src/components/logs/TektonTaskRunLog.tsx
- src/components/logs/logs-utils.ts
- src/components/utils/tekton-results.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-6363
`results.tekton.dev/record` annotation is used to get the Logs for the TaskRuns.
> SRVKP-6363: use TaskRuns `results.tekton.dev/record` annotation to get the logs

- src/components/text-column-field/drag-drop-context.tsx
**Fixes**: 
https://issues.redhat.com/browse/SRVKP-6343
**Analysis / Root cause**: 
`withDragDropContext` is not exposed to dynamic plugins. In start pipeline form, user can create secret, there again, another HTML5Backend was getting created and this lead to "Cannot have two HTML5 backends at the same time." error.
Ideally `DroppableFileInput` and `TextColumnField` should be exposed to dynamic plugins which internally uses DND but since these components are not exposed, this change is required to set the context to window.
`HTML5Backend` is passed directly as `backend` prop to `DndProvider` instead of `manager` prop and the `context` is set to `window`
**Screen shots / Gifs for design review**: 
----BEFORE--- …
> SRVKP-6343: Console crashes when ssh is selected in add secret for starting a pipeline run

- src/components/pipelineRuns-list/PipelineRunsList.tsx
- src/components/pipelines-tasks/TaskRunsList.tsx
- src/components/utils/tekton-results.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-6638
`VirtualizedTable` which is exposed to dynamic plugin is missing `onRowsRendered` prop which is available in `VirtualTableBody` of PatternFly. 
Created https://issues.redhat.com/browse/OCPBUGS-43538 ticket for that. 
Once this ticket is closed, instead of the solution provided in this PR we have to use `onRowsRendered` prop in `VirtualizedTable` to call `nextPageToken`.
**Demo:**
----PipelineRun list page---
https://drive.google.com/file/d/1HO6V5AnMSRqVgTTf1hAIT-COVCH2Q701/view?usp=drive_link
------
----TaskRun list page---
https://drive.google.com/file/d/1FlOn6Zp3aEKxFlAmivy1IiFRWUUYrPyk/view?usp=drive_link
> SRVKP-6638: PipelineRuns List page doesn't fetch next page data on scroll

- src/components/utils/proxy.ts
- src/components/utils/summary-api.ts
- src/components/utils/tekton-results.ts
Descriptions: Enable the `allowAuthHeader` in the internet proxy to send the token to Results API.
> SRVKP-6574: Pass token to Results API

- src/components/pipelineRuns-details/PipelineRunDetailsPage.tsx
- src/components/pipelineRuns-list/PipelineRunsKebab.tsx
- src/components/utils/utils.ts
- src/types/pipelineRun.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-6733
**Analysis / Root cause:**
PipelineRun with Resolver case was not handled. Only Pipeline name was sent at the time of rerun under pipelineRef.
**Solution Description:**
If PLR is using resolver, instead of sending pipeline name in pipelineRef, resolver and params values are used.
**Screen shots / Gifs for design review:**
**-----BEFORE-----**
----Rerun in PLR details page---
https://github.com/user-attachments/assets/5cb4a51b-4ef5-4c1c-aa46-131ab9f04bfd
----
----Rerun in PLR list page---
https://github.com/user-attachments/assets/f8ac7137-8723-42bd-a0fd-6e3c8b870d0a
----
**-----AFTER-----**
----Rerun in PLR details page---
https://github.com/user-attachments/assets/48a74912-cf12-48ca-ab3a-90c9f1030508
----
----Rerun in PLR list …
> SRVKP-6733: ReRun of Resolver based PipelineRuns fails from UI

- src/components/hooks/useTaskRuns.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-7594
Reverted loading logic change done in PR - https://github.com/openshift-pipelines/console-plugin/pull/421
> SRVKP-7594: PLR details page borken due to loading issue

- src/components/logs/LogSnippetBlock.tsx
- src/components/logs/LogSnippetFromPod.tsx
- src/components/logs/log-snippet-utils.ts
- src/components/pipelines-tasks/taskRunLogSnippet.ts
- src/types/log-snippet-types.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-4210
------**Before:**-----
--------------------------------------------
-----**After:**-----
**Note:**
I will create a PR to handle styling issues in details page.
> SRVKP-4210: Display a clear message populated on to the pipelinerun log snippet

- .gitignore
- integration-tests/cypress/features/pipelines/pipeline-overview.feature
- integration-tests/cypress/support/pages/functions/installOperatorOnClusterUsingCLI.ts
- integration-tests/cypress/support/pages/pipelines/task-page.ts
- integration-tests/cypress/support/step-definitions/pipelines/pipeline-overview.ts
- package.json
Issue: 
Story:[ODC-7593](https://issues.redhat.com/browse/ODC-7593)
Description:
Automation of pipeline-overview page
Command to execute:
export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.13-042801.devcluster.openshift.com/
export BRIDGE_KUBEADMIN_PASSWORD
export BRIDGE_BASE_ADDRESS
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
oc apply -f ./tests/utils/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./tests/utils/patch-htpasswd.yaml)" --type=merge
yarn run test-cypress
Run pipeline-overview.feature
Browser
Chrome 125
> ODC-7593: Automation of pipeline overview page

- console-extensions.json
- integration-tests/cypress/features/pipelines/pipeline-overview.feature
- package.json
- src/components/hooks/flagHookProvider.ts
- src/components/templates/index.ts
- src/components/templates/pipelines.ts
**Story:**
https://issues.redhat.com/browse/ODC-7788
Moved below extensions to console dynamic plugin
dev-console.add/action - already moved in first phase
console.yaml-template
console.flag/model
console.page/route - already moved in first phase
> ODC-7788: Contribute Pipeline related extensions from Pipelines console plugin

- src/components/catalog/apis/artifactHub.ts
- src/components/catalog/providers/useArtifactHubTasksProvider.tsx
- src/components/quick-search/QuickSearchContent.tsx
- src/components/quick-search/QuickSearchController.tsx
- src/components/quick-search/QuickSearchDetails.tsx
- src/components/quick-search/QuickSearchModal.tsx
- src/components/quick-search/QuickSearchModalBody.tsx
- src/components/quick-search/utils/quick-search-utils.tsx
- src/components/task-quicksearch/PipelineQuickSearch.tsx
- src/components/task-quicksearch/PipelineQuickSearchDetails.tsx
**Fixes:**
https://issues.redhat.com/browse/SRVKP-5546
Call to ArtifactHub was happening only once and if user search any task and if that task was not returned in first API call, the task was not listed in quick search. With this fix, if user searched something, API call will be made to ArtifactHub api and fetch the task
**Screen recording:**
> SRVKP-5546: Pipelines builder shows only some tasks from hubs

- src/components/pipelineRuns-details/PipelineRunDetails.tsx
- src/components/pipelines-details/PipelineDetails.tsx
- src/components/pipelines-tasks/tasks-details-pages/TaskRunDetailsSection.tsx
- src/components/tasks/TaskDetails.tsx
**Before:**
- Task details page
- TaskRun details page
- PipelineRun details page
- Pipeline details page
**After:**
- Task details page
- TaskRun details page
- PipelineRun details page
- Pipeline details page
> SRVKP-8351: Fix details page item alignment

- src/components/approval-tasks/ApprovalTasksList.tsx
This patch fixes any partially approved pipelinerun to show in the 
pending category of manual approval gate pipelinerun UI filter
fixes: [SRVKP-8256](https://issues.redhat.com/browse/SRVKP-8256)
After fix:
> SRVKP-8256: Fix manual approval gate pipelinerun UI filer

- src/components/pipelineRuns-list/usePipelineRunsColumns.ts
- src/components/pipelines-details/__tests__/pipeline-step-utils.spec.ts
- src/components/pipelines-details/pipeline-step-utils.ts
Description of problem:
Sorting PipelineRuns by duration sorts strings, not actual duration. So for example PipelineRun with duration "5 minutes 36 seconds" is sorted above "40 seconds" and that is above "2 minutes 44 seconds".
Prerequisites (if any, like setup, operators/versions):
Red Hat OpenShift Pipelines - 5.0.5-369 provided by Red Hat
OpenShift version 4.14.33
Steps to Reproduce
Have a multiple PipelineRuns running with wide range of durations
Go to https://console-openshift-console..../pipelines/all-namespaces/pipeline-runs?orderBy=desc&sortBy=Duration
> SRVKP-6211: sorting pipelineruns by duration sorts strings, not actual duration

- .konflux/dockerfiles/console-plugin.Dockerfile
> chore(KONFLUX-6210): fix and set name and cpe label for console-plugin-1-14-console-plugin

- .konflux/dockerfiles/console-plugin.Dockerfile
> chore(KONFLUX-6210): fix and set name and cpe label for console-plugin-1-15-console-plugin

- .konflux/dockerfiles/console-plugin.Dockerfile
> chore(KONFLUX-6210): fix and set name and cpe label for console-plugin-1-16-console-plugin

- .konflux/dockerfiles/console-plugin.Dockerfile
> chore(KONFLUX-6210): fix and set name and cpe label for console-plugin-1-17-console-plugin

- .konflux/dockerfiles/console-plugin.Dockerfile
> chore(KONFLUX-6210): fix and set name and cpe label for console-plugin-1-18-console-plugin
