openshift-pipelines/console-plugin

OWNERS
=> Update OWNERS file to map the team working on it

package.json, src/components/hooks/useTektonResults.ts, src/components/utils/proxy.ts, src/components/utils/tekton-results.ts, src/models.ts, src/types/computedStatus.ts, src/types/coreTekton.ts, src/types/hub.ts, src/types/index.ts, src/types/pipeline.ts, src/types/pipelineResource.ts, src/types/pipelineRun.ts, src/types/task.ts, src/types/taskRun.ts, yarn.lock
Adds Hooks to fetch TaskRuns and PipelineRuns from tektonResults API.
=> ODC-7408: add tektonResults hooks

build.sh
This adds a script to build and push image to `quay.io/openshift-pipeline`
=> Add script to build and push image to quay.io

src/components/pipelines-metrics/PipelinesMetricsPage.tsx, src/components/pipelines-overview/PipelineRunsDurationCard.tsx, src/components/pipelines-overview/PipelineRunsNumbersChart.tsx, src/components/pipelines-overview/PipelineRunsStatusCard.tsx, src/components/pipelines-overview/PipelineRunsTotalCard.tsx, src/components/pipelines-overview/PipelinesOverviewPage.tsx, src/components/pipelines-overview/utils.ts
#22 Had an issue with PR, so making another.
=> Added Interval for Duration,TotalRuns,NoOfPipelineRuns & Status

src/components/pipelines-metrics/PipelinesMetricsPage.tsx, src/components/pipelines-overview/PipelineRunsStatusCard.tsx, src/components/pipelines-overview/PipelinesOverviewPage.tsx, src/components/pipelines-overview/SearchInput.tsx, src/components/pipelines-overview/dateTime.ts, src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesList.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesRow.tsx, src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx, src/components/pipelines-overview/utils.ts, src/components/utils/tekton-results.ts
**Story:**
https://issues.redhat.com/browse/ODC-7442
**Demo:** 
https://drive.google.com/file/d/1wOU249jQTvxGh1kX9QouOWPelp8_M0Us/view?usp=drive_link
=> ODC-7442: Integrate the tektonResults API in the PipelineRuns list

src/components/pipelines-overview/PipelineRunsDurationCard.tsx, src/components/pipelines-overview/PipelineRunsNumbersChart.tsx, src/components/pipelines-overview/PipelineRunsStatusCard.tsx, src/components/pipelines-overview/PipelineRunsTotalCard.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesList.tsx, src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
**Demo:**
https://drive.google.com/file/d/1E7jx-xWiXOSWLG60YjusAb_fRPhwTfav/view?usp=drive_link
=> ODC-7458: Added inline loading for all components

src/components/pipelines-overview/PipelineRunsNumbersChart.tsx, src/components/pipelines-overview/PipelineRunsStatusCard.tsx
https://drive.google.com/file/d/1XzBy5XWB3lPEI_zz7zxBoOxw-E7VqVUW/view?usp=sharing
=> OCPBUGS-25334: shows correct data on BarCharts

src/components/pipelines-metrics/PipelinesAverageDuration.tsx, src/components/pipelines-overview/PipelineRunsNumbersChart.tsx, src/components/pipelines-overview/PipelineRunsStatusCard.tsx
=> fix: chart tick style padding fix

src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesRow.tsx
Added link to total runs in list page to redirect to plr tab
=> fix: Added link to total runs in list page to redirect to plr tab

src/components/pipelines-overview/dateTime.ts, src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesList.tsx, src/components/pipelines-overview/utils.ts
**Story**: https://issues.redhat.com/browse/ODC-7472
**Demo**: 
https://drive.google.com/file/d/1SfWxkJRDA_pg716LThne-txk7U_XJS9s/view?usp=drive_link
=> ODC-7472: Update last run time to support unix timestamp

.gitignore, __mocks__/dummy.ts, __mocks__/react-i18next.ts, __mocks__/serverFlags.js, jest.config.ts, package.json, src/components/pipelines-overview/PipelineRunsDurationCard.tsx, src/components/pipelines-overview/PipelineRunsNumbersChart.tsx, src/components/pipelines-overview/PipelineRunsStatusCard.tsx, src/components/pipelines-overview/PipelineRunsTotalCard.tsx, src/components/pipelines-overview/__tests__/PipelinesOverview.spec.tsx, src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx, tsconfig.json, yarn.lock
Add and setup react testing library for the components unit tests.
=> ODC-7416: Add react testing library for unit tests

src/components/pipelines-overview/PipelineRunsStatusCard.tsx
**Story**: https://issues.redhat.com/browse/ODC-7469
**Demo**: https://drive.google.com/file/d/1sf6dleit6emYxtG4LAC3KNVH8NitFV4k/view?usp=drive_link
Note: 
For 1 day filter, the line is not seen. It will not be the case if we merge https://issues.redhat.com/browse/ODC-7470
=> ODC-7469: Use line chart for PipelineRun status

src/components/pipelines-metrics/PipelinesAverageDuration.tsx, src/components/pipelines-overview/PipelineRunsNumbersChart.tsx, src/components/pipelines-overview/PipelineRunsStatusCard.tsx, src/components/pipelines-overview/PipelinesOverview.scss, src/components/pipelines-overview/dateTime.ts
**Story**: https://issues.redhat.com/browse/ODC-7466
**Screenshots**:
--**Before**---
--**After**---
=> ODC-7466: Fix design issue as per the UX design

i18n-scripts/build-i18n.sh, package.json, src/components/pipelines-overview/PipelineRunsStatusCard.tsx, src/components/pipelines-overview/utils.ts, test-frontend.sh, test-prow-e2e.sh, yarn.lock
=> Fix (hopefully some) issues with updated CI config

scripts/build_container.sh
* my bad I didn't rename the docker file location on #65
* in this PR I fixed the docker file location
=> SRVKP-4088: [main] fix dockerfile location

locales/en/plugin__pipelines-console-plugin.json, src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx, src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx, src/models.ts, src/types/openshift.ts
**Issue**: https://issues.redhat.com/browse/OCPBUGS-30160
**Description**: As developer user, cluster version is not accessible from config.openshift.io resource. So added to fetch from window.SERVER_FLAGS
=> OCPBUGS-30160: Non-admin users are not able to see overview page

package.json, src/components/yaml-editor/ResourceYAMLEditorViewOnly.tsx, yarn.lock
=> OCPBUGS-31884: Make TaskRuns YAML readOnly

src/components/logs/LogsWrapperComponent.tsx
Before:
https://github.com/openshift-pipelines/console-plugin/assets/2561818/d50aca6e-e8e1-461c-8231-eebb2850c503
After:
https://github.com/openshift-pipelines/console-plugin/assets/2561818/c25256d9-4875-47c5-909c-6a4a61118336
=> OCPBUGS-33238: Show same task name on terminal header and in task navigation

src/components/modals/LoadingModal.tsx, src/components/pipelines-list/PipelineKebab.tsx, src/components/start-pipeline/AddTriggerModal.tsx, src/components/start-pipeline/StartPipelineModal.tsx
Before:
https://github.com/openshift-pipelines/console-plugin/assets/2561818/d190b90f-c549-440c-ac3a-6df8c5c639e8
After:
https://github.com/openshift-pipelines/console-plugin/assets/2561818/064bee13-88bb-41ff-bdb4-7bd307b19f41
=> OCPBUGS-33257: Fix loader for start pipeline and add trigger modal

src/components/approval-tasks/ApprovalRow.scss, src/components/utils/__tests__/pipeline-approval-utils.spec.ts, src/components/utils/pipeline-approval-utils.ts
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-34180
Update the Current Status Column text and fix the alignment issue observed in Firefox
**Screen shots / Gifs for design review**: 
**Unit test coverage report**: 
Fixed.
**Test setup:**
1. Install the Pipelines Operator
2. Install Approval-Gates controller from this link: https://github.com/openshift-pipelines/manual-approval-gate/releases/download/v0.2.0/release-openshift.yaml
3. Create Sample Pipeline: https://gist.github.com/Lucifergene/f491504d7eda8a97e86a132029a9bc7b
4. Open Approval List page in **FIREFOX**.
**Browser conformance**:
=> OCPBUGS-34180: [CONSOLE-PLUGIN] Update the Current Status Column text and fix the alignment issue observed in Firefox

src/components/hooks/useTaskRuns.ts, src/components/hooks/useTektonResult.ts
**Issue:** 
https://issues.redhat.com/browse/OCPBUGS-34479
**Video:**
--Before--
https://drive.google.com/file/d/16npbmf2v3LNLgUH5xslvS7W6e8A-bimk/view?usp=drive_link
--After--
https://drive.google.com/file/d/1vr8w2mvm1KKo7_3KheBdDiFfpSadp3PE/view?usp=drive_link
=> [console-plugin] OCPBUGS-34479: Internet call happens in loop in PipelineRun list page

src/components/pipelineRuns-list/PipelineRunsRow.tsx
Static plugin PR: https://github.com/openshift/console/pull/13806
=> OCPBUGS-34574: TaskRuns should not be fetched for Failed PLR's

src/components/pipelines-details/PipelineDetailsPage.tsx
Fixes: [SRVKP-5769](https://issues.redhat.com/browse/SRVKP-5769)
https://github.com/openshift/console/assets/2561818/6b61284b-32da-4ebf-88e9-1122e039ff6e
=> SRVKP-5769: Fix Edit Pipeline option link on Pipeline details page

src/components/pipeline-topology/PipelineTaskNode.tsx, src/components/pipeline-topology/utils.ts
Issue:
https://issues.redhat.com/browse/OCPBUGS-36260
Screenshots:
=> OCPBUGS-36260: Tooltip on Pipeline when expression is not shows

package.json, src/components/pipelineRuns-list/PipelineRunsList.tsx, src/components/pipelines-list/PipelinesList.tsx, src/components/pipelines-tasks/TaskRunsList.tsx, yarn.lock
**Issue:**
https://issues.redhat.com/browse/OCPBUGS-33521
Pipeline list page - by default sorting will happen on `Last run time` column
PipelineRun list page - by default sorting will happen on `Started` column
TaskRun list page - by default sorting will happen on `Started` column
=> OCPBUGS-33521: Update sorting in pipeline, pipelineRun and TaskRun list pages

src/components/logs/Logs.tsx, src/components/logs/logs-utils.ts
Fixes: [SRVKP-5784](https://issues.redhat.com/browse/SRVKP-5784)
Screenshots:
=> SRVKP-5784: Add timestamps in the PipelineRuns logs

README.md
=> NO-JIRA: update readme: replace wip note with a feature list

src/components/common/StorageClassDropdown.tsx
=> SRVKP-5881: Fix StorageClass dropdown to show in volumeClaimTemplate form

integration-tests/cypress/features/pipelines/data-source-filter.feature, integration-tests/cypress/support/step-definitions/pipelines/data-source-filter.ts, integration-tests/cypress/testData/pipeline-with-pipelinerun-tasrun.yaml
**Story:**
https://issues.redhat.com/browse/ODC-7598
**Tests:**
=> ODC-7598: Added e2e tests for data source filter group

package.json, yarn.lock
Fixes: [SRVKP-6177](https://issues.redhat.com/browse/SRVKP-6177)
This PR fixes 2 critical vulnerabilities
Before:
After:
=> SRVKP-6177: Fix CVE-2024-43788 and CVE-2024-29041

src/components/utils/tekton-results.ts
**Story:**
https://issues.redhat.com/browse/SRVKP-5774
**Demo:**
https://drive.google.com/file/d/1xLS0U3K76CBynM3jeVoCjfrkKNYvymz8/view?usp=drive_link
=> SRVKP-5774: Add support for v1 api support in Pipeline dashboard

package.json, yarn.lock
**Fixes:**
https://issues.redhat.com/browse/SRVKP-6677
----Before----
----After
=> SRVKP-6677: Tekton UI bug in openshift pipelines while using "array" params

console-extensions.json, src/components/pipelines-overview/NamespaceDropdown.tsx, src/components/pipelines-overview/PipelinesOverviewPage.tsx, src/components/pipelines-overview/PipelinesOverviewPageK8s.tsx, src/components/projects-list/AllProjectsPage.tsx
**Fixes:** 
https://issues.redhat.com/browse/SRVKP-6637
----Admin user---
https://drive.google.com/file/d/1FKw1trTy3Gu9Tv0EhRr6_1S_ONhtbQK-/view?usp=drive_link
----Non-admin user who don't have access to All namespace---
https://drive.google.com/file/d/1uh-uwrxNtGNvg0Pd4z-in2vQJJf-LInh/view?usp=drive_link
=> SRVKP-6637: Remove All options from project dropdown on overview page for user have no access to all projects

OWNERS
This is aligned with
* https://github.com/openshift/console/pull/14425
* https://github.com/openshift/console-operator/pull/936
=> NO-JIRA: Update owners file after I changed my GitHub username

nginx.conf
Fixes https://issues.redhat.com/browse/SRVKP-6741
=> SRVKP-6741: Remove duplicate root attribute in nginx.conf

integration-tests/cypress/support/pages/pipelines/pipelineBuilder-page.ts, src/components/pipeline-topology/InstallingNodeDecorator.tsx, src/components/pipeline-topology/StatusIcons.tsx, src/components/pipelines-details/PipelineVisualizationTask.tsx, src/components/pipelines-details/StatusIcon.tsx, src/components/status/StatusIconAndText.tsx, src/components/styles/common.scss
Changed co-spin classname to co-spin-pipelines to aviod conflict with console class name
=> SRVKP-6898: Replace font awesome with custom css in dynamic plugin #204

integration-tests/cypress/support/pages/pipelines/pipelineBuilder-page.ts, src/components/pipeline-topology/InstallingNodeDecorator.tsx, src/components/pipeline-topology/StatusIcons.tsx, src/components/pipelines-details/PipelineVisualizationTask.tsx, src/components/pipelines-details/StatusIcon.tsx, src/components/status/StatusIconAndText.tsx, src/components/styles/common.scss
Manual cherrypick of https://github.com/openshift-pipelines/console-plugin/pull/204 and https://github.com/openshift-pipelines/console-plugin/pull/206
=> [release-1.17.x] SRVKP-6901: Replace font awesome with custom css in dynamic plugin

src/components/outputs/OutputTab.tsx, src/components/outputs/ResultsList.tsx
**Issue:**
https://issues.redhat.com/browse/SRVKP-7063
**Before:**
**After:**
=> SRVKP-7063: UI- results not displayed when pipeline run fails

src/components/approval-tasks/ApprovalTasksList.tsx, src/components/list-pages/ListPage.scss, src/components/multi-tab-list/MultiTabListPage.scss, src/components/pipeline-builder/OptionalableWorkspace.tsx, src/components/pipeline-builder/PipelineBuilderEditPage.scss, src/components/pipeline-builder/modals/ModalContent.scss, src/components/pipeline-builder/modals/index.tsx, src/components/pipeline-builder/task-sidebar/TaskSidebar.scss, src/components/pipeline-builder/task-sidebar/TaskSidebarHeader.scss, src/components/pipeline-builder/task-sidebar/TaskSidebarWhenExpression.scss, src/components/pipeline-topology/CustomTaskNode.scss, src/components/pipelineRuns-list/PipelineRunsList.scss, src/components/pipelineRuns-list/PipelineRunsList.tsx, src/components/pipelines-list/PipelinesList.tsx, src/components/pipelines-tasks/tasks-details-pages/TaskRunDetailsPage.scss, src/components/projects-list/AllProjectsPage.scss, src/components/projects-list/ProjectsList.tsx, src/components/repositories-list/RepositoriesList.tsx, src/components/shortcuts/Shortcut.scss
**Fixes**: 
https://issues.redhat.com/browse/ODC-7762
**Analysis / Root cause**: 
Some of the classnames are not updated to use PF5 classnames.
Updated the classnames.
=> ODC-7762: [Pipelines] Update the PF4 class name in Pipelines console plugin

charts/openshift-console-plugin/templates/configmap.yaml, charts/openshift-console-plugin/templates/deployment.yaml
=> OCPBUGS-51120: Detect ipv4/ipv6 socket in pod ip for nginx conf

src/components/pipelineRuns-details/utils.ts, src/components/pipelines-details/utils.ts, src/components/triggers-details/DynamicResourceLinkList.tsx, src/components/triggers-details/PipelineResourceRef.tsx
**Fixes:**
https://issues.redhat.com/browse/SRVKP-7295
**Demo:**
https://drive.google.com/file/d/1uVBhwy6U7LqE_gfFsF4kWkH4yWVcngPX/view?usp=drive_link
=> SRVKP-7295: UI link in pipeline run points to v1beta1 pipeline

src/components/hooks/useTaskRuns.ts, src/components/pipelines-tasks/TaskRunsList.tsx, src/consts.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-7409
**Demo:**
https://github.com/user-attachments/assets/53848a0a-1603-446b-bd55-318e38e33ffc
=> SRVKP-7409: OpenShift Pipelines / Tekton Results shows TaskRuns from previous PipelineRuns of the same name

src/components/layout/PaneBody.tsx, src/components/pipeline-builder/CodeEditorField.scss, src/components/pipeline-builder/CodeEditorField.tsx, src/components/pipeline-builder/PipelineBuilderForm.tsx, src/components/pipeline-builder/sidebars/resource-sidebar-samples.tsx, src/components/pipeline-builder/sidebars/resource-sidebar.tsx, src/components/pipeline-builder/sidebars/simple-tab-nav.tsx
**Fixes:**
https://issues.redhat.com/browse/SRVKP-7598
Fixed styling in Pipeline builder yaml form
**Demo:**
----4.18----PF5--
------
---main---PF6--
=> SRVKP-7598: Broken style in console-plugin

src/components/start-pipeline/validation-utils.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-7613
Due to the yup version upgrade, validation error shows up in start pipeline form. Updated the schema to handle both string and array types for parameters
**-------------Before:------------**
**------------After:----------**
=> SRVKP-7613: Unable to start pipeline from UI because of param type error

src/components/hooks/useTaskRuns.ts, src/components/start-pipeline/validation-utils.ts
**Fixes:**
https://issues.redhat.com/browse/SRVKP-7752
https://issues.redhat.com/browse/SRVKP-7751
**Screenshots/Video:**
----BEFORE----
https://github.com/user-attachments/assets/3287aaa0-f876-480b-873c-1299ce67c309
https://github.com/user-attachments/assets/780defe0-26e9-4097-af42-39f7abf07594
----------------
-----AFTER------
https://github.com/user-attachments/assets/5a2426c8-babf-4314-85a3-16b93460dd55
https://github.com/user-attachments/assets/b55f707c-679d-450b-bb45-4eef73ba04ef
=> SRVKP-7752,SRVKP-7751:Pipelines page loading issue in 1.19

src/components/approval-tasks/ApprovalTaskActionDropdown.tsx, src/components/approval-tasks/approval-notification/pipeline-approval-context.tsx, src/components/hooks/hooks.ts, src/components/pipeline-overview/TriggerLastRunButton.tsx, src/components/pipelineRuns-details/PipelineRunDetailsPage.tsx, src/components/pipelineRuns-list/PipelineRunsKebab.tsx, src/components/pipelineRuns-list/PipelineRunsList.tsx, src/components/pipelineRuns-list/PipelineRunsRow.tsx, src/components/pipelines-details/PipelineDetailsPage.tsx, src/components/pipelines-list/PipelineKebab.tsx, src/components/pipelines-list/PipelineRow.tsx, src/components/pipelines-list/PipelinesList.tsx, src/components/start-pipeline/AddTriggerModal.tsx, src/components/start-pipeline/StartPipelineModal.tsx, src/components/start-pipeline/submit-utils.ts, src/components/start-pipeline/utils.ts, src/components/utils/pipelines-actions.tsx, src/components/utils/utils.ts
Descriptions: The PipelineRun `pipeline.openshift.io/started-by` annotation was not updated when the user re-ran the Pipeline.
https://github.com/user-attachments/assets/f019531d-3561-4347-ac81-fb6b955bedad
=> SRVKP-8114: Fix PipelineRun pipeline.openshift.io/started-by annotation

src/components/pipelines-tasks/tasks-details-pages/events/event-stream.tsx, src/components/pipelines-tasks/tasks-details-pages/events/toggle-play.jsx, src/components/pipelines-tasks/tasks-details-pages/events/toggle-play.scss
Fixes: https://issues.redhat.com/browse/SRVKP-8158
=> SRVKP-8158: Fix PLR and TR events page

src/components/pipeline-builder/PipelineBuilderHeader.tsx, src/components/pipelineRuns-details/PipelineRunDetails.tsx, src/components/pipelines-details/PipelineDetails.tsx, src/components/pipelines-overview/PipelinesOverviewPage.tsx, src/components/pipelines-overview/PipelinesOverviewPageK8s.tsx
**Fixes:**
https://issues.redhat.com/browse/SRVKP-8206
Removed extra spaces in h2 headings
=> SRVKP-8206: Extra space in h2 headings

src/components/quick-search/QuickSearchModalBody.tsx
**Fixes:**
https://issues.redhat.com/browse/SRVKP-8208
**Video:**
=> SRVKP-8208: Redhat provided tasks are not appearing in task search in pipeline builder page

src/components/quick-search/QuickSearchModalBody.tsx, src/components/quick-search/utils/quick-search-utils.tsx
**Fixes:**
https://issues.redhat.com/browse/SRVKP-8210
**Video:**
=> SRVKP-8210: User can not select any task in search result of tasks in pipeline builder page
